.PHONY: default looping memset clean all

default:
	gcc -o aufgabe2 aufgabe2.c

looping:
	gcc -o aufgabe2_looping aufgabe2_looping.c

memset:
	gcc -o aufgabe2_memset aufgabe2_memset.c

clean:
	rm aufgabe2_memset aufgabe2_looping aufgabe2

all: default looping memset

