all:
	gcc -o aufgabe2_looping aufgabe2_looping.c
	gcc -o aufgabe2_memset aufgabe2_memset.c

looping:
	gcc -o aufgabe2_looping aufgabe2_looping.c

memset:
	gcc -o aufgabe2_memset aufgabe2_memset.c

clean:
	rm aufgabe2_memset aufgabe2_looping
